-- Every syncable entity owns UUID identity, audit timestamps, delete marker and optimistic sync metadata.
CREATE TABLE IF NOT EXISTS accounts (id TEXT PRIMARY KEY, display_name TEXT NOT NULL, email_address TEXT NOT NULL UNIQUE, imap_host TEXT NOT NULL, imap_port INTEGER NOT NULL, smtp_host TEXT NOT NULL, smtp_port INTEGER NOT NULL, encryption TEXT NOT NULL, auth_kind TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT, sync_status TEXT NOT NULL DEFAULT 'pending', sync_version INTEGER NOT NULL DEFAULT 1, server_id TEXT);
CREATE TABLE IF NOT EXISTS email_folders (id TEXT PRIMARY KEY, account_id TEXT NOT NULL REFERENCES accounts(id), name TEXT NOT NULL, role TEXT, remote_id TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT, sync_status TEXT NOT NULL DEFAULT 'pending', sync_version INTEGER NOT NULL DEFAULT 1, server_id TEXT);
CREATE TABLE IF NOT EXISTS contacts (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT, phone TEXT, department TEXT, position TEXT, company TEXT, notes TEXT, avatar_path TEXT, favorite INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT, sync_status TEXT NOT NULL DEFAULT 'pending', sync_version INTEGER NOT NULL DEFAULT 1, server_id TEXT);
CREATE TABLE IF NOT EXISTS conversations (id TEXT PRIMARY KEY, kind TEXT NOT NULL, title TEXT, channel_slug TEXT, description TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT, sync_status TEXT NOT NULL DEFAULT 'pending', sync_version INTEGER NOT NULL DEFAULT 1, server_id TEXT);
CREATE TABLE IF NOT EXISTS messages (id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL REFERENCES conversations(id), sender_id TEXT, body TEXT NOT NULL, reply_to_id TEXT REFERENCES messages(id), sent_at TEXT, edited_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT, sync_status TEXT NOT NULL DEFAULT 'pending', sync_version INTEGER NOT NULL DEFAULT 1, server_id TEXT);
CREATE TABLE IF NOT EXISTS sync_queue (id TEXT PRIMARY KEY, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, operation TEXT NOT NULL, payload TEXT NOT NULL, attempt_count INTEGER NOT NULL DEFAULT 0, next_attempt_at TEXT, last_error TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(entity_type, entity_id, operation));
CREATE INDEX IF NOT EXISTS idx_messages_conversation_sent ON messages(conversation_id, sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_sync_queue_next_attempt ON sync_queue(next_attempt_at);
