use chrono::{Duration, Utc};
use rusqlite::{params, Connection};
use crate::error::AppError;

pub fn seed_development_data(connection: &Connection) -> Result<(), AppError> {
  let count: i64 = connection.query_row("SELECT COUNT(*) FROM accounts", [], |row| row.get(0))?;
  if count > 0 { return seed_messenger(connection); }
  let now = Utc::now(); let account_id = "dev-account"; let folder_id = "dev-inbox";
  connection.execute("INSERT INTO accounts (id, display_name, email_address, imap_host, imap_port, smtp_host, smtp_port, encryption, auth_kind, status, created_at, updated_at, sync_status) VALUES (?1, 'Alex Morgan', 'alex@northstar.test', 'localhost', 993, 'localhost', 465, 'tls', 'password', 'offline', ?2, ?2, 'synced')", params![account_id, now.to_rfc3339()])?;
  connection.execute("INSERT INTO email_folders (id, account_id, name, role, created_at, updated_at, sync_status) VALUES (?1, ?2, 'Inbox', 'inbox', ?3, ?3, 'synced')", params![folder_id, account_id, now.to_rfc3339()])?;
  connection.execute("INSERT INTO email_folders (id, account_id, name, role, created_at, updated_at, sync_status) VALUES ('dev-drafts', ?1, 'Drafts', 'drafts', ?2, ?2, 'synced')", params![account_id, now.to_rfc3339()])?;
  connection.execute("INSERT INTO email_folders (id, account_id, name, role, created_at, updated_at, sync_status) VALUES ('dev-sent', ?1, 'Sent', 'sent', ?2, ?2, 'synced')", params![account_id, now.to_rfc3339()])?;
  connection.execute("INSERT INTO email_folders (id, account_id, name, role, created_at, updated_at, sync_status) VALUES ('dev-archive', ?1, 'Archive', 'archive', ?2, ?2, 'synced')", params![account_id, now.to_rfc3339()])?;
  connection.execute("INSERT INTO email_folders (id, account_id, name, role, created_at, updated_at, sync_status) VALUES ('dev-trash', ?1, 'Trash', 'trash', ?2, ?2, 'synced')", params![account_id, now.to_rfc3339()])?;
  let messages = [("Maya Chen", "maya@northstar.test", "Q3 planning: a few decisions to close", "The updated Q3 planning document is ready for review. I added the notes from our leadership sessions and highlighted the three decisions we need to close this week."), ("Diego Alvarez", "diego@northstar.test", "Re: Design system audit", "Great catch on the form states. I added a few thoughts in the document for the next pass."), ("People Operations", "people@northstar.test", "Open enrollment starts Monday", "Your benefits enrollment window opens next week. Here is what to know."), ("Priya Nair", "priya@northstar.test", "Research partnership update", "The team at Solace confirmed a meeting for Thursday afternoon.")];
  for (index, (name, email, subject, body)) in messages.into_iter().enumerate() { let timestamp = (now - Duration::minutes((index * 73) as i64)).to_rfc3339(); let thread: Option<String> = if index == 0 { Some("thread-q3".into()) } else if index == 1 { Some("thread-design".into()) } else { None }; connection.execute("INSERT INTO emails (id, account_id, folder_id, sender_name, sender_email, subject, body_text, thread_id, received_at, is_read, is_starred, created_at, updated_at, sync_status) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?9, ?9, 'synced')", params![format!("dev-email-{index}"), account_id, folder_id, name, email, subject, body, thread, timestamp, (index > 0) as i64, (index == 1) as i64])?; }
  let draft_timestamp = (now - Duration::minutes(12)).to_rfc3339();
  connection.execute("INSERT INTO emails (id, account_id, folder_id, subject, body_text, received_at, is_read, created_at, updated_at, direction, delivery_state, sync_status) VALUES ('dev-draft', ?1, ?2, 'Release notes draft', 'Hi team,' || char(10) || char(10) || 'Here are the release notes for the next build.', ?3, 1, ?3, ?3, 'outbound', 'draft', 'synced')", params![account_id, "dev-drafts", draft_timestamp])?;
  connection.execute("INSERT INTO email_recipients (id, email_id, recipient_type, email_address, created_at) VALUES ('dev-draft-r1', 'dev-draft', 'to', 'maya@northstar.test', ?1)", params![draft_timestamp])?;
  let sent_timestamp = (now - Duration::hours(5)).to_rfc3339();
  connection.execute("INSERT INTO emails (id, account_id, folder_id, subject, body_text, thread_id, received_at, is_read, created_at, updated_at, direction, delivery_state, sync_status) VALUES ('dev-sent-1', ?1, ?2, 'Re: Q3 planning: a few decisions to close', 'Looks good to me. I will update the tracker today.', 'thread-q3', ?3, 1, ?3, ?3, 'outbound', 'queued', 'synced')", params![account_id, "dev-sent", sent_timestamp])?;
  connection.execute("INSERT INTO email_recipients (id, email_id, recipient_type, email_address, created_at) VALUES ('dev-sent-r1', 'dev-sent-1', 'to', 'maya@northstar.test', ?1)", params![sent_timestamp])?;
  seed_messenger(connection)
}
fn seed_messenger(connection: &Connection) -> Result<(), AppError> {
  let count: i64 = connection.query_row("SELECT COUNT(*) FROM conversations WHERE id = 'dev-general'", [], |row| row.get(0))?;
  if count > 0 { return Ok(()); }
  let now = Utc::now();
  for (id, name, email, department, position) in [("dev-self", "Alex Morgan", "alex@northstar.test", "IT", "IT Manager"), ("dev-maya", "Maya Chen", "maya@northstar.test", "Product", "Product Lead"), ("dev-diego", "Diego Alvarez", "diego@northstar.test", "Operations", "Supervisor"), ("dev-priya", "Priya Nair", "priya@northstar.test", "Research", "Researcher"), ("dev-nina", "Nina Patel", "nina@northstar.test", "Accounting", "Accountant")] { connection.execute("INSERT OR IGNORE INTO contacts (id, name, email, department, position, created_at, updated_at, sync_status) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?6, 'synced')", params![id, name, email, department, position, now.to_rfc3339()])?; }
  connection.execute("INSERT INTO conversations (id, kind, title, channel_slug, description, created_at, updated_at, sync_status) VALUES ('dev-general', 'channel', 'General', 'general', 'Company-wide conversation', ?1, ?1, 'synced')", params![now.to_rfc3339()])?;
  connection.execute("INSERT INTO conversations (id, kind, title, channel_slug, description, created_at, updated_at, sync_status) VALUES ('dev-it-support', 'channel', 'IT Support', 'it-support', 'Servers, deployments and tooling help', ?1, ?1, 'synced')", params![now.to_rfc3339()])?;
  connection.execute("INSERT INTO conversations (id, kind, title, channel_slug, description, created_at, updated_at, sync_status) VALUES ('dev-announcements', 'channel', 'Announcements', 'announcements', 'Company news and updates', ?1, ?1, 'synced')", params![now.to_rfc3339()])?;
  for member in ["dev-self", "dev-maya", "dev-diego", "dev-priya", "dev-nina"] { connection.execute("INSERT INTO channel_members (channel_id, contact_id, role, joined_at) VALUES ('dev-general', ?1, 'member', ?2)", params![member, now.to_rfc3339()])?; }
  for member in ["dev-self", "dev-diego"] { connection.execute("INSERT INTO channel_members (channel_id, contact_id, role, joined_at) VALUES ('dev-it-support', ?1, 'member', ?2)", params![member, now.to_rfc3339()])?; }
  for member in ["dev-self", "dev-maya", "dev-nina"] { connection.execute("INSERT INTO channel_members (channel_id, contact_id, role, joined_at) VALUES ('dev-announcements', ?1, 'member', ?2)", params![member, now.to_rfc3339()])?; }
  for (index, (conversation, sender, body)) in [("dev-general", "dev-maya", "Welcome to the new local-first workspace. Please share feedback here."), ("dev-general", "dev-diego", "I added the deployment notes to the operations folder."), ("dev-general", "dev-self", "Thanks — I will review the notes this afternoon."), ("dev-it-support", "dev-diego", "Server maintenance will start at 10 PM tonight."), ("dev-announcements", "dev-maya", "Security training is scheduled for Thursday.")].into_iter().enumerate() { let timestamp = (now - Duration::minutes((45 - index * 9) as i64)).to_rfc3339(); connection.execute("INSERT INTO messages (id, conversation_id, sender_id, body, thread_id, sent_at, created_at, updated_at, sync_status) VALUES (?1, ?2, ?3, ?4, ?1, ?5, ?5, ?5, 'synced')", params![format!("dev-message-{index}"), conversation, sender, body, timestamp])?; }
  // Replies all point at the same thread root (`thread_id` = dev-message-3),
  // including the nested one, which answers a reply rather than the root;
  // `in_reply_to` keeps the exact parent for the quoted context in the UI.
  for (index, (sender, body)) in [("dev-maya", "Noted."), ("dev-priya", "Will monitor."), ("dev-diego", "Thanks."), ("dev-self", "I will handle the database.")].into_iter().enumerate() { let timestamp = (now - Duration::minutes((5 - index) as i64)).to_rfc3339(); connection.execute("INSERT INTO messages (id, conversation_id, sender_id, body, reply_to_id, in_reply_to, thread_id, sent_at, created_at, updated_at, sync_status) VALUES (?1, 'dev-it-support', ?2, ?3, 'dev-message-3', 'dev-message-3', 'dev-message-3', ?4, ?4, ?4, 'synced')", params![format!("dev-reply-{index}"), sender, body, timestamp])?; }
  connection.execute("INSERT INTO messages (id, conversation_id, sender_id, body, reply_to_id, in_reply_to, thread_id, sent_at, created_at, updated_at, sync_status) VALUES ('dev-reply-nested', 'dev-it-support', 'dev-diego', 'Agreed, I will confirm once the migration window closes.', 'dev-reply-0', 'dev-reply-0', 'dev-message-3', ?1, ?1, ?1, 'synced')", params![(now - Duration::minutes(3)).to_rfc3339()])?;
  connection.execute("INSERT INTO conversations (id, kind, created_at, updated_at, sync_status) VALUES ('dev-dm-maya', 'dm', ?1, ?1, 'synced')", params![now.to_rfc3339()])?;
  for member in ["dev-self", "dev-maya"] { connection.execute("INSERT INTO channel_members (channel_id, contact_id, role, joined_at) VALUES ('dev-dm-maya', ?1, 'member', ?2)", params![member, now.to_rfc3339()])?; }
  for (index, (sender, body)) in [("dev-maya", "Do you have a minute to review the rollout checklist?"), ("dev-self", "Yes - sending you notes before standup.")].into_iter().enumerate() { let timestamp = (now - Duration::minutes((20 - index * 4) as i64)).to_rfc3339(); connection.execute("INSERT INTO messages (id, conversation_id, sender_id, body, thread_id, sent_at, created_at, updated_at, sync_status) VALUES (?1, 'dev-dm-maya', ?2, ?3, ?1, ?4, ?4, ?4, 'synced')", params![format!("dev-dm-{index}"), sender, body, timestamp])?; }
  connection.execute("UPDATE messages SET pinned_at = ?1 WHERE id = 'dev-message-3'", params![now.to_rfc3339()])?;
  connection.execute("INSERT INTO notifications (id, kind, title, body, entity_type, entity_id, is_read, created_at) VALUES ('dev-notification-welcome', 'message', 'New message in #general', 'Maya Chen: Welcome to the new local-first workspace.', 'conversation', 'dev-general', 0, ?1)", params![now.to_rfc3339()])?;
  connection.execute("INSERT INTO notifications (id, kind, title, body, entity_type, entity_id, is_read, created_at) VALUES ('dev-notification-mention', 'mention', 'Maya mentioned you in #announcements', 'Maya Chen: Security training is scheduled for Thursday.', 'conversation', 'dev-announcements', 0, ?1)", params![now.to_rfc3339()])?;
  for (key, value) in [("presence.status", "online"), ("theme", "system"), ("density", "comfortable"), ("font_size", "13")] { connection.execute("INSERT OR IGNORE INTO settings (key, value, updated_at) VALUES (?1, ?2, ?3)", params![key, value, now.to_rfc3339()])?; }
  connection.execute("INSERT OR IGNORE INTO settings (key, value, updated_at) VALUES ('presence.since', ?1, ?2)", params![now.to_rfc3339(), now.to_rfc3339()])?;
  Ok(())
}
